[2025-03-15T22:29:23.815+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_data_ingestion.ingest_order_items_data manual__2025-03-15T22:29:09.734679+00:00 [queued]>
[2025-03-15T22:29:23.869+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_data_ingestion.ingest_order_items_data manual__2025-03-15T22:29:09.734679+00:00 [queued]>
[2025-03-15T22:29:23.875+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-03-15T22:29:23.968+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): ingest_order_items_data> on 2025-03-15 22:29:09.734679+00:00
[2025-03-15T22:29:24.008+0000] {standard_task_runner.py:57} INFO - Started process 332 to run task
[2025-03-15T22:29:24.014+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_data_ingestion', 'ingest_order_items_data', 'manual__2025-03-15T22:29:09.734679+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpeu4mvggy']
[2025-03-15T22:29:24.087+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask ingest_order_items_data
[2025-03-15T22:29:24.529+0000] {logging_mixin.py:149} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-15T22:29:25.743+0000] {task_command.py:410} INFO - Running <TaskInstance: postgres_data_ingestion.ingest_order_items_data manual__2025-03-15T22:29:09.734679+00:00 [running]> on host d1d9f3f582cd
[2025-03-15T22:29:27.361+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Blessing' AIRFLOW_CTX_DAG_ID='postgres_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_order_items_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-15T22:29:09.734679+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-15T22:29:09.734679+00:00'
[2025-03-15T22:29:29.127+0000] {logging_mixin.py:149} INFO - Ingesting data into the 'order_items' table...
[2025-03-15T22:29:40.686+0000] {logging_mixin.py:149} INFO - Data successfully ingested into the 'order_items' table.
[2025-03-15T22:29:40.705+0000] {python.py:183} INFO - Done. Returned value was: Successfully ingested order_items
[2025-03-15T22:29:40.750+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=postgres_data_ingestion, task_id=ingest_order_items_data, execution_date=20250315T222909, start_date=20250315T222923, end_date=20250315T222940
[2025-03-15T22:29:40.776+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-03-15T22:29:40.803+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
